"""Statistics-first city simulation package."""

from city_simulator.agents import (
    Agent,
    HouseholdAgent,
    LivingConditions,
    OrganizationAgent,
    PersonAgent,
    living_conditions_for,
)
from city_simulator.citizens import (
    Citizen,
    advance_citizen_histories,
    generate_representative_citizens,
)
from city_simulator.model import (
    ANNUAL_TURN_STEPS,
    CityMetrics,
    CityPolicy,
    CityRevenueSources,
    CitySensitivity,
    CityState,
    DelayedEffect,
    Demographics,
    EmbeddedService,
    FinancialInstitutionProfile,
    HousingAssistance,
    HousingStock,
    Issue,
    ModelParameters,
    Neighborhood,
    OperatingSchedule,
    PlaceAsset,
    PressureLedger,
    YearResult,
    ZoningEnvelope,
    active_delayed_effects,
    simulate,
)
from city_simulator.person_generator import (
    FamilyGenerationSpec,
    GeneratedFamily,
    GeneratedFamilyPopulation,
    generate_family_agents,
    generate_family_population,
)
from city_simulator.scenario import ScenarioError, load_city, load_scenario
from city_simulator.starter import STARTER_PRESETS, starter_city, write_starter_city
from city_simulator.views import PopulationStructureView, View
from city_simulator.work_catalog import (
    BusinessType,
    JobTemplate,
    business_type_for,
    eligible_job_template_for,
    job_template_for,
)

__all__ = [
    "ANNUAL_TURN_STEPS",
    "STARTER_PRESETS",
    "Agent",
    "BusinessType",
    "Citizen",
    "CityMetrics",
    "CityPolicy",
    "CityRevenueSources",
    "CitySensitivity",
    "CityState",
    "DelayedEffect",
    "Demographics",
    "EmbeddedService",
    "FamilyGenerationSpec",
    "FinancialInstitutionProfile",
    "GeneratedFamily",
    "GeneratedFamilyPopulation",
    "HouseholdAgent",
    "HousingAssistance",
    "HousingStock",
    "Issue",
    "JobTemplate",
    "LivingConditions",
    "ModelParameters",
    "Neighborhood",
    "OperatingSchedule",
    "OrganizationAgent",
    "PersonAgent",
    "PlaceAsset",
    "PopulationStructureView",
    "PressureLedger",
    "ScenarioError",
    "View",
    "YearResult",
    "ZoningEnvelope",
    "active_delayed_effects",
    "advance_citizen_histories",
    "business_type_for",
    "eligible_job_template_for",
    "generate_family_agents",
    "generate_family_population",
    "generate_representative_citizens",
    "job_template_for",
    "living_conditions_for",
    "load_city",
    "load_scenario",
    "simulate",
    "starter_city",
    "write_starter_city",
]
